name: reuse-workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The artifact name
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifacts@v3
        with:
          name: {{ inputs.artifact-name }}
      - name: output contents
        run: ls
      - name: Depploy
        run: echo 'deploying......'
  report:
    runs-on: ubuntu-latest
    steps:
      - name: running report
        run: echo 'generating report'
