name: reuse-workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The artifact name
        required: true
        type: string
    secrets:
      S0ME_SECRET:
        required: true
    outputs:
      job-status:
        description: responds with a job status
        value: ${{jobs.deploy.outputs.jobstatus}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      jobstatus: ${{ steps.result1.outputs.jobstatus}}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: output contents
        run: ls
      - name: printing secret
        run: echo " MY SEECRET IS ${{secrets.SOME_SECRET}}"
      - name: Depploy
        run: echo 'deploying......'
      - name: set result output
        id: result1
        run: echo "jobstatus=success" >> $GITHUB_OUTPUT
  report:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: running report
        run: echo 'generating report'
