name: reuse-workflow
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: does nothing
        run: echo 'do nothing'
  report:
    runs-on: ubuntu-latest
    steps:
      - name: running report
        run: echo 'generating report'
